//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string ClientId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public Nullable<int> AdministratorId { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
